[project]
name = "aoc-2025"
version = "0.1.0"
description = "Advent of Code 2025"
readme = "README.md"
requires-python = ">=3.15"
dependencies = []

[dependency-groups]
dev = [
    "line-profiler>=5.0.0",
]
